name: Bug Report
description: Report a problem or unexpected behavior
title: "[BUG]: "
labels:
  - bug

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue clearly
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      placeholder: |
        1. Open Blender
        2. Load file
        3. Start render
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What should happen?
